server:
  port: 8762
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
 # profiles:
 #   active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smile2sm/config.git
          username: smile2.sm@qq.com
          password: gan13878533932
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
          
          
          
          